//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "matchy_meetup_pair_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pair_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub discord_uid: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::matchy_meetup_pair::Entity",
        from = "Column::PairId",
        to = "super::matchy_meetup_pair::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MatchyMeetupPair,
}

impl Related<super::matchy_meetup_pair::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchyMeetupPair.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
