//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod matchy_meetup_opt_in;
pub mod matchy_meetup_pair;
pub mod matchy_meetup_pair_member;
pub mod matchy_meetup_round;
pub mod snipe_opt_out;
pub mod social_team_pairing_entry;
pub mod social_team_pairing_group;
pub mod social_team_pairing_round;
pub mod spotting_message;
pub mod spotting_victim;
pub mod user_stat;
