//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "social_team_pairing_round")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::social_team_pairing_group::Entity")]
    SocialTeamPairingGroup,
}

impl Related<super::social_team_pairing_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SocialTeamPairingGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
