//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "social_team_pairing_entry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_id: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub team_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::social_team_pairing_group::Entity",
        from = "Column::GroupId",
        to = "super::social_team_pairing_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SocialTeamPairingGroup,
}

impl Related<super::social_team_pairing_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SocialTeamPairingGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
