//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "social_team_pairing_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub round_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::social_team_pairing_entry::Entity")]
    SocialTeamPairingEntry,
    #[sea_orm(
        belongs_to = "super::social_team_pairing_round::Entity",
        from = "Column::RoundId",
        to = "super::social_team_pairing_round::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SocialTeamPairingRound,
}

impl Related<super::social_team_pairing_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SocialTeamPairingEntry.def()
    }
}

impl Related<super::social_team_pairing_round::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SocialTeamPairingRound.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
