//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "spotting_message")]
pub struct Model {
    pub guild_id: i64,
    pub channel_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub message_id: i64,
    pub author_id: i64,
    pub time_posted: DateTime,
    pub is_social: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::spotting_victim::Entity")]
    SpottingVictim,
}

impl Related<super::spotting_victim::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpottingVictim.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
