//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "spotting_victim")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub message_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub victim_id: i64,
    #[sea_orm(column_type = "Float", nullable)]
    pub latitude: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub longitude: Option<f32>,
    pub notes: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spotting_message::Entity",
        from = "Column::MessageId",
        to = "super::spotting_message::Column::MessageId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SpottingMessage,
}

impl Related<super::spotting_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpottingMessage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
